### ISSUE TITLE
Endpoint for PlayerMMR is invalid

### ISSUE THREAD

**Issue by tbitowt** [Teo230/Valorant.Rest.API#1]
Looks like API endpoint for PlayerMMR is the same as for CompetitiveMatch.

The endpoint mmr/v1/players/{playerId}/competitiveupdates is working for CompetetiveMatch, but PlayerMMR DTO does not fit to returned json data.

**Comment by Teo230** [comment]
Check @RumbleMike Valorant API Wiki for more information, clone the repo of my custom API Wrapper, fix it, and create a pull request. At the moment my time is very limited
